services:
  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  infinity:
    image: michaelf34/infinity:latest
    platform: linux/amd64
    ports:
      - "7997:7997"
    command: >
      v2
      --model-id BAAI/bge-small-en-v1.5
      --model-id cross-encoder/ms-marco-MiniLM-L-6-v2
      --port 7997

volumes:
  chroma_data:
  ollama-data: