resolvers:
  local:
    base_path: /tmp

loaders:
  pdf:
    page_separator: "\n"

embedder:
  provider: huggingface
  huggingface:
    model: BAAI/bge-small-en-v1.5
    batch_size: 64

vectorstore:
  provider: chroma
  chroma:
    persist_directory: .chroma
    collection_name: rag_collection
    distance_function: cosine

retriever:
  provider: hybrid
  vector:
    score_threshold: null
  hybrid:
    top_k: 5
    fetch_k: 20 # overrides the top_k of vector and bm25 retrievers